export const SavingBox = [
    {
       "type":"impl",
       "name":"SavingBox",
       "interface_name":"___testsingle::ISavingBox"
    },
    {
       "type":"struct",
       "name":"core::integer::u256",
       "members":[
          {
             "name":"low",
             "type":"core::integer::u128"
          },
          {
             "name":"high",
             "type":"core::integer::u128"
          }
       ]
    },
    {
       "type":"enum",
       "name":"core::bool",
       "variants":[
          {
             "name":"False",
             "type":"()"
          },
          {
             "name":"True",
             "type":"()"
          }
       ]
    },
    {
       "type":"interface",
       "name":"___testsingle::ISavingBox",
       "items":[
          {
             "type":"function",
             "name":"get_samount",
             "inputs":[
                
             ],
             "outputs":[
                {
                   "type":"core::integer::u256"
                }
             ],
             "state_mutability":"view"
          },
          {
             "type":"function",
             "name":"get_number_of_payments",
             "inputs":[
                
             ],
             "outputs":[
                {
                   "type":"core::integer::u64"
                }
             ],
             "state_mutability":"view"
          },
          {
             "type":"function",
             "name":"get_payment_interval",
             "inputs":[
                
             ],
             "outputs":[
                {
                   "type":"core::integer::u64"
                }
             ],
             "state_mutability":"view"
          },
          {
             "type":"function",
             "name":"get_start_time",
             "inputs":[
                
             ],
             "outputs":[
                {
                   "type":"core::integer::u64"
                }
             ],
             "state_mutability":"view"
          },
          {
             "type":"function",
             "name":"get_user_data",
             "inputs":[
                {
                   "name":"user_address",
                   "type":"core::starknet::contract_address::ContractAddress"
                }
             ],
             "outputs":[
                {
                   "type":"(core::integer::u256, core::integer::u64, core::integer::u64, core::bool)"
                }
             ],
             "state_mutability":"view"
          },
          {
             "type":"function",
             "name":"get_registered_users",
             "inputs":[
                
             ],
             "outputs":[
                {
                   "type":"core::array::Array::<core::starknet::contract_address::ContractAddress>"
                }
             ],
             "state_mutability":"view"
          },
          {
             "type":"function",
             "name":"advance_payment",
             "inputs":[
                
             ],
             "outputs":[
                
             ],
             "state_mutability":"external"
          },
          {
             "type":"function",
             "name":"get_expected_payments",
             "inputs":[
                {
                   "name":"timestamp",
                   "type":"core::integer::u64"
                }
             ],
             "outputs":[
                {
                   "type":"core::integer::u64"
                }
             ],
             "state_mutability":"view"
          },
          {
             "type":"function",
             "name":"get_current_payment",
             "inputs":[
                
             ],
             "outputs":[
                {
                   "type":"core::integer::u64"
                }
             ],
             "state_mutability":"view"
          },
          {
             "type":"function",
             "name":"pay",
             "inputs":[
                
             ],
             "outputs":[
                
             ],
             "state_mutability":"external"
          },
          {
             "type":"function",
             "name":"early_withdraw",
             "inputs":[
                {
                   "name":"num_payments",
                   "type":"core::integer::u64"
                }
             ],
             "outputs":[
                
             ],
             "state_mutability":"external"
          },
          {
             "type":"function",
             "name":"withdraw",
             "inputs":[
                
             ],
             "outputs":[
                
             ],
             "state_mutability":"external"
          },
          {
             "type":"function",
             "name":"get_withdraw_fee",
             "inputs":[
                
             ],
             "outputs":[
                {
                   "type":"core::integer::u64"
                }
             ],
             "state_mutability":"view"
          },
          {
             "type":"function",
             "name":"get_total_fees_collected",
             "inputs":[
                
             ],
             "outputs":[
                {
                   "type":"core::integer::u256"
                }
             ],
             "state_mutability":"view"
          },
          {
             "type":"function",
             "name":"get_token_address",
             "inputs":[
                
             ],
             "outputs":[
                {
                   "type":"core::starknet::contract_address::ContractAddress"
                }
             ],
             "state_mutability":"view"
          },
          {
             "type":"function",
             "name":"get_vesu_address",
             "inputs":[
                
             ],
             "outputs":[
                {
                   "type":"core::starknet::contract_address::ContractAddress"
                }
             ],
             "state_mutability":"view"
          },
          {
             "type":"function",
             "name":"donate",
             "inputs":[
                {
                   "name":"amount",
                   "type":"core::integer::u256"
                }
             ],
             "outputs":[
                
             ],
             "state_mutability":"external"
          }
       ]
    },
    {
       "type":"constructor",
       "name":"constructor",
       "inputs":[
          {
             "name":"save_amount",
             "type":"core::integer::u256"
          },
          {
             "name":"number_of_payments",
             "type":"core::integer::u64"
          },
          {
             "name":"payment_interval",
             "type":"core::integer::u64"
          },
          {
             "name":"withdraw_fee",
             "type":"core::integer::u64"
          },
          {
             "name":"token_address",
             "type":"core::starknet::contract_address::ContractAddress"
          },
          {
             "name":"vesu_address",
             "type":"core::starknet::contract_address::ContractAddress"
          }
       ]
    },
    {
       "type":"event",
       "name":"___testsingle::SavingBox::Event",
       "kind":"enum",
       "variants":[
          
       ]
    }
 ]